### ISSUE TITLE
Restrictive license

### ISSUE THREAD

**Issue by VladMarius** [Zolmeister/pond#3]
Hello , really great code, but the license you use is among the most restrictive open-source licenses for getting your code/work known. Could you maybe consider using a MIT license or a BSD license? The many restrictions imposed by GLP could be resolved with just a google search and a MIT (or BSD license).

Please consider this , as it's good code that deserves more exposure.

**Comment by Zolmeister** [comment]
The code is mostly not re-usable and is game specific.
For that reason, I see no value in releasing the game under a more permissive license.

If there is a specific snippet that someone finds valuable they can raise an issue and I will re-consider.
